
GET /cars HTTP/1.1
Host: localhost:8080

POST /cars HTTP/1.1
Host: localhost:8080
Content-Type: application/json

 {
    "tipo": {
      "marca": "Mercedes",
      "referencia": "G63",
      "modelo": "2022",
      "carroceria": "SUV"
    },
    "especificaciones": {
      "potencia": "100 HP",
      "torque": "100 N/m",
      "transmision": "At",
      "motor": "2.5 lt",
      "pasajeros": "7 Pasajeros",
      "combustible": "Extra",
      "consumo": "50 Km/Galon",
      "almacenamiento": "150 litros"
    },
    "infoadicional": {
      "descripcion": "Chimba de Carro",
      "lujo": 1,
      "ddeportivo": 0
    }
  }